### ISSUE TITLE
Optional override Consul RESTful HTTP API URI doesn't seem to working

### ISSUE THREAD

**Issue by jennyfountain** [jenkinsci/consul-kv-builder-plugin#7]
I cannot get get the local code override to work. It returns the value from the server specified globally.

Here is the code 

`node {
    wrap([$class: 'ConsulKVReadWrapper', reads: [[aclToken: 'tokenstuff', urlOverride: 'http://consul.url:8500', apiUri: 'http://consul.url:8500', debugMode: 'ENABLED', envKey: 'a_active_key', hostUrl: 'http://consul.url:8500', key: "ecs/aside/active"]]]) {
        echo env.a_active_key
    }
}`

Not sure what I am missing.  I am using jenkins 2.70.

Thanks!

**Comment by jimmyraywv** [comment]
@jennyfountain 

So, I am using 2.73.1, with the below code, and it worked to lookup 2 keys:

`wrap([$class: 'ConsulKVReadWrapper', reads: [[aclToken: '<SOME_TOKEN>', apiUri: '', debugMode: 'ENABLED', envKey: 'TEST_KEY', hostUrl: 'http://<SOME_HOST>:8500', ignoreGlobalSettings: true, key: 'test/test-key'], [aclToken: '<SOME_TOKEN>', apiUri: '', debugMode: 'ENABLED', envKey: 'TEST_KEY2', hostUrl: '<SOME_HOST>', ignoreGlobalSettings: true, key: 'test/test-key-2']]]) {
    echo env.TEST_KEY
    echo env.TEST_KEY2
}`


I think you are missing __ignoreGlobalSettings: true__ and your __apiUri__ can be blank, if it is the default _"/v1/kv/"_.  You have the __hostUrl__ value duplicated in the __apiUri__.

**Comment by jennyfountain** [comment]
Works Great! Thank you! I didn't see that in the docs.
